apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
spec:
  capacity: 
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /storage
    server: 192.168.42.1
  persistentVolumeReclaimPolicy: Recycle
