kind: Pod
apiVersion: v1
metadata:
   name: nfs-pv-pod
spec:
  volumes:
    - name: nfs-pv
      persistentVolumeClaim:
        claimName: nfs-pv-claim
  containers:
    - name: nfs-client1
      image: toccoag/openshift-nginx
      ports:
        - containerPort: 8081
          name: "http-server1"
      volumeMounts:
        - mountPath: "/nfsshare"
          name: nfs-pv
      resources: {} 
    - name: nfs-client2
      image: toccoag/openshift-nginx
      ports:
        - containerPort: 8082
          name: "http-server2"
      volumeMounts:
        - mountPath: "/nfsshare"
          name: nfs-pv
      resources: {}
