apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple1
    name: simple1
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple1
    name: simple1
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: simple1:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/sandervanvugt/simpleapp
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.1
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: BLGUor2JhlTRm4huxtPz
      type: GitHub
    - generic:
        secret: IXpudEnNs6_i6FRwkvBk
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple1
    name: simple1
  spec:
    replicas: 1
    selector:
      app: simple1
      deploymentconfig: simple1
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: simple1
          deploymentconfig: simple1
      spec:
        containers:
        - image: simple1:latest
          name: simple1
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - simple1
        from:
          kind: ImageStreamTag
          name: simple1:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple1
    name: simple1
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: simple1
      deploymentconfig: simple1
  status:
    loadBalancer: {}
kind: List
metadata: {}
