kind: Template
apiVersion: v1
metadata:
  name: demo-template
labels:
  role: web
message: Deploying ${WEB_SERVER}
objects:
  - kind: Pod
    apiVersion: v1
    metadata:
      name: tdemo-pod
    spec:
      containers:
        - name: ${WEB_SERVER}
          image: ${WEB_SERVER}
  - kind: Service
    apiVersion: v1
    metadata:
      name: tdemo-svc
    spec:
      ports:
        - port: 80
      selector:
        role: web
  - kind: Route
    apiVersion: v1
    metadata:
      name: tdemo-route
    spec:
      to:
        kind: Service
        name: tdemo-svc
parameters:
  - name: WEB_SERVER
    displayName: Web Server
    description: Web server image to use
    value: nginx
