apiVersion: v1
kind: Pod
metada:
  name: mywebserver
  labels: 
    name: webserver
spec:
  containers:
    - name: webserver
      image: httpd:latest
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: volume-web
          MountPath: /var/www/html
      volumes:
        - name: volume-web
          persistentVolumeClaim:
            claimName: web-pvc
